// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9cqi2ZMGbNO3Y90CTiX4aidHsIt2h7IQ',
    appId: '1:417584734853:web:dcc89acb94bc0304ed7fec',
    messagingSenderId: '417584734853',
    projectId: 'deardiary2-7698a',
    authDomain: 'deardiary2-7698a.firebaseapp.com',
    storageBucket: 'deardiary2-7698a.appspot.com',
    measurementId: 'G-EDYGDZ03L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTbnAxzWw2gALzDM_Knt0CK8PRsXVeL_g',
    appId: '1:417584734853:android:d3058e99e9a5ca29ed7fec',
    messagingSenderId: '417584734853',
    projectId: 'deardiary2-7698a',
    storageBucket: 'deardiary2-7698a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjW0bhrc0XedwNHDwj2YkAcrZ9aSB6DMM',
    appId: '1:417584734853:ios:754f8d4f661a926aed7fec',
    messagingSenderId: '417584734853',
    projectId: 'deardiary2-7698a',
    storageBucket: 'deardiary2-7698a.appspot.com',
    iosBundleId: 'com.example.dearr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjW0bhrc0XedwNHDwj2YkAcrZ9aSB6DMM',
    appId: '1:417584734853:ios:754f8d4f661a926aed7fec',
    messagingSenderId: '417584734853',
    projectId: 'deardiary2-7698a',
    storageBucket: 'deardiary2-7698a.appspot.com',
    iosBundleId: 'com.example.dearr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9cqi2ZMGbNO3Y90CTiX4aidHsIt2h7IQ',
    appId: '1:417584734853:web:38b4bd3bc8495752ed7fec',
    messagingSenderId: '417584734853',
    projectId: 'deardiary2-7698a',
    authDomain: 'deardiary2-7698a.firebaseapp.com',
    storageBucket: 'deardiary2-7698a.appspot.com',
    measurementId: 'G-YY4ZX6FD4Y',
  );
}
